apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: notification-reminders
  namespace: default
spec:
  pubsubname: kafka-pubsub
  topic: reminders
  route: /reminders
scopes:
  - notification-service
