apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: recurring-task-events
  namespace: default
spec:
  pubsubname: kafka-pubsub
  topic: task-events
  route: /task-events
scopes:
  - recurring-service
