apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.recurringService.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: recurring-service
spec:
  type: {{ .Values.recurringService.service.type }}
  ports:
    - port: {{ .Values.recurringService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: recurring-service
